### ISSUE TITLE
Header fonts

### ISSUE THREAD

**Issue by savvylee11** [amaliaks/Final_Project_Amalia#1]
I would change the header fonts for the slogan on your site. It's kind of hard to read due to the curly script and the light pink. If it were either a little more plan or darker you could probably get away with it. 

I like that your site as a very set personality, and you don't need to scrub that... but making some of the fonts more reader friendly might help in the future. 

Overall the look and feel of your site is really nice! I enjoyed looking though it.

**Comment by amaliaks** [comment]
Thanks!! I ended up changing the fonts and the colors to make them darker
