### ISSUE TITLE
Adding Categories? 

### ISSUE THREAD

**Issue by tatyanaberdan** [amaliaks/Final_Project_Amalia#10]
Congrats on creating three different custom post types!  I know the struggle of making those :)

I would recommend adding categories to your blog since you have three different types of posts and separate subjects that you're covering (recipes, tv shows, restaurants) in each. Having categories that show up below/above your recent posts and recent comments in the sidebar would make it easier to navigate the blog.

**Comment by amaliaks** [comment]
Hey Tatyana! Thanks!! Definitely going to look to added the categories, I just ran out of time this time. Stay tuned!
