### ISSUE TITLE
Navigation bar text and custom post type

### ISSUE THREAD

**Issue by jaclynglover** [amaliaks/Final_Project_Amalia#11]
You already know that I think you did an awesome job on your site. You created not one, not two, but THREE custom post types. A TON of work. Some suggestions/ideas for improvement:
- You mentioned this was a trouble area, but you might consider playing around a bit more with your main navigation bar to get the text to center rather than be left justified.
- You could also consider making the color of your site subtitle a little bit of a darker color, just to make it stand out more (because we are all food and TV junkies at heart, right?).
- Another suggestion would be to make the photos within your restaurant review posts just a little bit larger.
- Lastly, I want to take a closer look at your custom post type code to figure out what the issue is. Feel free to take a look at mine here on GitHub, because I changed it around a bit since the last time we had our coding study session. 

Great job!

**Comment by amaliaks** [comment]
Thank you, Jaclyn!!! I was able to change the font and color of the navigation and headline to make it easier to read. I will also be doing these updates, these are great suggestions! Stay tuned for phase 2 of the site :)
