### ISSUE TITLE
Feedback!

### ISSUE THREAD

**Issue by mollykorroch** [amaliaks/Final_Project_Amalia#12]
Nice job! I’m impressed by all the detailed customizations you made—and all the content examples you have. You’ve got so many different elements, and it’s making me really hungry to see all the restaurants you’ve experienced! Only suggestion I really have is to change the menu bar text to a font that isn’t a script and to maybe use some text spacing and more contrasting colors—just to make it easier to read.

**Comment by amaliaks** [comment]
Hey Molly! I ended up doing both! I changed the font and the colors. Great idea :)
