### ISSUE TITLE
Feedback!

### ISSUE THREAD

**Issue by vkinnealey** [amaliaks/Final_Project_Amalia#2]
Awesome site with a lot of good content! I would maybe update the font to match the title (which you mentioned in your presentation) and potentially get the 'recent posts' to break out by topic area (e.g. tv, recipes, restaurant) but otherwise looks great!

**Comment by amaliaks** [comment]
Thanks, Victoria! I ended up changing the title/fonts. I wasn't able to add a category for the recent post, but I plan on doing that in phase 2.
