### ISSUE TITLE
Feedback:)

### ISSUE THREAD

**Issue by alliefoard** [amaliaks/Final_Project_Amalia#4]
Hey! 

I really loved how you decided to incorporate movies and restaurants to your blog. The last time we spoke it was just going to be about recipes and cooking, so I think it made it a lot more well-rounded now. I think what stood out to me within your code were the post types that you created. Although parts of them that didn't work it showed the effort that you put in to try and make them.

**Comment by amaliaks** [comment]
Hi Allie!! Thanks so much!
