### ISSUE TITLE
A Couple Notes

### ISSUE THREAD

**Issue by xof88** [amaliaks/Final_Project_Amalia#5]
Hi Amalia! Really great work on your site! I think you got the most up there of anyone in the class! I have a couple notes for you to take or leave as you wish:
1. On your Home page, try moving the feature image of a cake down below the page header. I didn't see it was the homepage until I scrolled down and saw Home. (similar to your About me page)
2. Your T.V. Reviews page could use a background color to make the reviews pop! Maybe that pretty blue from your title?
3. Add some pretty photos of the yummy food on your Recipe page:)
4. Great restaurant review! You're going to love Sushi Taro - get the omakase.

Best of luck!
Jane

**Comment by amaliaks** [comment]
Thanks, Jane! I am definitely planning on doing all of this is phase 2! I wasn't able to get it all done before the Sunday deadline
